name: Latest blog articles
on:
  schedule: 
    - cron: '0 * * * *' 
  workflow_dispatch: 
jobs:
  update-hashnode-blog:
    name: Update this repo's README with the latest hashnode blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://arindam1729.hashnode.dev/rss.xml"
