name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # Runs Every 24 Hours

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'Arindam1729' # Hashnode Username
          COUNT: 4 # MAX Visisble
          STYLE: "blog-grid-2"
          BLOG_URL: "https://arindam1729.hashnode.dev/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
